version: "3.8"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.repo=/snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./snapshots:/snapshots

volumes:
  esdata01:
